// 用語カード拡充スクリプト
// 既存の terms.json（15枚）を保持しつつ、高頻出サービス/概念を追加する。
// id 重複は既存を優先。CLF-C02 の頻出項目を網羅する。
//   node design/build_terms.js
const fs = require("fs");
const path = require("path");
const ROOT = path.join(__dirname, "..");
const file = path.join(ROOT, "Resources/terms.json");
const existing = JSON.parse(fs.readFileSync(file, "utf8"));

const T = (id, term, domain, difficulty, shortDescription, beginnerExplanation, useCase, examPoint, relatedServices) =>
  ({ id, term, shortDescription, beginnerExplanation, useCase, examPoint, relatedServices, domain, difficulty });

const added = [
  // ---------------- technology ----------------
  T("t-dynamodb", "Amazon DynamoDB", "technology", 2,
    "フルマネージドのNoSQLデータベース。",
    "表計算のような「行と列」ではなく、キーで超高速に読み書きできるデータベースです。サーバー管理不要で、アクセスが増えても自動で対応します。",
    "大量アクセスのアプリ、ゲームのスコア、IoTデータなど、高速・大規模なデータ保存。",
    "キー・バリュー型NoSQL。サーバーレスで自動スケール。RDS（SQL）との対比で頻出。",
    ["RDS", "Aurora"]),
  T("t-aurora", "Amazon Aurora", "technology", 2,
    "AWSが最適化した高性能なリレーショナルDB。",
    "MySQLやPostgreSQLと互換性がありつつ、AWSが速度と可用性を大幅に高めたデータベースです。",
    "高い性能と可用性が必要な業務システムのSQLデータベース。",
    "RDSの上位。高可用・高性能なマネージドSQL。MySQL/PostgreSQL互換。",
    ["RDS", "DynamoDB"]),
  T("t-ebs", "Amazon EBS", "technology", 2,
    "EC2に接続して使う仮想ディスク。",
    "EC2（仮想サーバー）に取り付ける外付けハードディスクのようなもの。OSやデータを保存します。",
    "EC2で動くサーバーのシステム領域やデータ領域。",
    "ブロックストレージ。基本1つのEC2に接続。スナップショットでバックアップ可能。EFSとの違いに注意。",
    ["EC2", "S3"]),
  T("t-efs", "Amazon EFS", "technology", 2,
    "複数サーバーから共有できるファイルストレージ。",
    "1つのファイル置き場を、たくさんのEC2から同時に読み書きできる共有フォルダのようなサービスです。",
    "複数サーバーで同じファイルを共有したいとき。",
    "ファイルストレージ。多数のEC2から同時マウント可能。EBS（専用）との違いが定番。",
    ["EBS", "EC2"]),
  T("t-fargate", "AWS Fargate", "technology", 2,
    "サーバー管理不要でコンテナを動かす仕組み。",
    "コンテナ（アプリを箱詰めしたもの）を動かすとき、土台のサーバーを自分で用意・管理せずに済ませられるサービスです。",
    "コンテナを運用したいがサーバー管理はしたくないとき。",
    "ECS/EKSのサーバーレス実行環境。サーバー管理不要＝Fargate。",
    ["ECS", "Lambda"]),
  T("t-beanstalk", "AWS Elastic Beanstalk", "technology", 2,
    "コードを上げるだけでアプリを公開できるPaaS。",
    "サーバーやロードバランサーの準備をAWSに任せ、プログラムをアップするだけでWebアプリを公開できるサービスです。",
    "インフラ構築に手間をかけず素早くアプリを公開したいとき。",
    "PaaS。裏側のEC2/ELB等を自動構成。手早い公開＝Beanstalk。",
    ["EC2", "ELB"]),
  T("t-cloudformation", "AWS CloudFormation", "technology", 2,
    "インフラ構成をコードで自動構築（IaC）。",
    "サーバーやネットワークの構成をテンプレート（設計図のコード）に書いておけば、同じ環境を何度でも自動で作れます。",
    "同じ構成を再現したい、手作業のミスを無くしたいとき。",
    "Infrastructure as Code（IaC）の代表。テンプレートから自動構築。",
    ["Systems Manager"]),
  T("t-autoscaling", "Amazon EC2 Auto Scaling", "technology", 2,
    "負荷に応じてサーバー台数を自動増減。",
    "アクセスが増えたらEC2を自動で増やし、減ったら減らす仕組み。混雑にもコストにも対応します。",
    "アクセス変動の大きいサービスで、性能とコストを両立したいとき。",
    "弾力性（エラスティシティ）の代表例。ELBと組み合わせて高可用性を実現。",
    ["ELB", "EC2"]),
  T("t-elb", "Elastic Load Balancing", "technology", 2,
    "アクセスを複数サーバーに振り分ける装置。",
    "たくさんの利用者からのアクセスを、複数のサーバーへ均等に配分します。1台が故障しても他へ回すので止まりにくくなります。",
    "サーバーを複数台に分散して可用性を上げたいとき。",
    "ロードバランサー。ALB＝HTTP向け、NLB＝高速TCP向け。高可用性の要。",
    ["EC2", "Auto Scaling"]),
  T("t-athena", "Amazon Athena", "technology", 2,
    "S3のデータを直接SQLで分析。",
    "S3にためたデータを、データベースへ移さずそのままSQLで検索・集計できるサービスです。サーバー準備は不要。",
    "S3のログやデータを手軽に分析したいとき。",
    "サーバーレス分析。S3を直接クエリ。手軽な分析＝Athena。",
    ["S3", "Glue"]),
  T("t-redshift", "Amazon Redshift", "technology", 2,
    "大規模データを高速分析するデータウェアハウス。",
    "膨大なデータをまとめて保管し、集計・分析に特化した高速なデータベースです。",
    "全社データの本格的な分析・BIレポート作成。",
    "データウェアハウス（DWH）。大規模分析＝Redshift。Athenaとの使い分けが定番。",
    ["Athena", "QuickSight"]),
  T("t-kinesis", "Amazon Kinesis", "technology", 3,
    "リアルタイムに流れるデータを処理。",
    "センサーやログのように絶え間なく届くデータを、その場で受け取って処理・分析できるサービスです。",
    "リアルタイムのログ収集、ストリーミングデータ処理。",
    "ストリーミングデータ処理。リアルタイム＝Kinesis。",
    ["Redshift"]),
  T("t-sagemaker", "Amazon SageMaker", "technology", 3,
    "機械学習モデルを作る総合環境。",
    "AIの「学習・作成・公開」を一通り行える土台。自分でモデルを作りたいときに使います。",
    "独自の機械学習モデルを構築・運用したいとき。",
    "MLの構築〜デプロイを一気通貫。自前でモデル作成＝SageMaker。",
    ["Bedrock"]),
  T("t-bedrock", "Amazon Bedrock", "technology", 2,
    "生成AIをAPIで手軽に使えるサービス。",
    "文章や画像を生成するAI（基盤モデル）を、難しい準備なしにアプリから呼び出して使えるサービスです。",
    "チャットや文章生成などの生成AI機能をアプリに組み込みたいとき。",
    "生成AIの入り口＝Bedrock。複数の基盤モデルをAPIで利用。",
    ["SageMaker"]),
  T("t-apigateway", "Amazon API Gateway", "technology", 2,
    "APIの受付窓口を作るサービス。",
    "アプリの外部からのリクエストを受け付け、LambdaなどのバックエンドにつなぐAPIの玄関口です。",
    "サーバーレスAPIやマイクロサービスの入口を作りたいとき。",
    "APIの窓口。Lambdaと組み合わせてサーバーレス構成に。",
    ["Lambda"]),
  T("t-sqs", "Amazon SQS", "technology", 2,
    "処理待ちメッセージをためるキュー。",
    "処理をすぐに実行せず、いったん行列（キュー）に並べて、受け手が自分のペースで取り出せるようにする仕組みです。",
    "システム同士を切り離して、負荷の波を吸収したいとき。",
    "メッセージキュー。疎結合の要。ためる＝SQS。",
    ["SNS", "Lambda"]),
  T("t-sns", "Amazon SNS", "technology", 2,
    "1つの通知を複数へ一斉配信。",
    "あるできごとを、メールや他サービスなど複数の宛先へ一度に知らせる仕組み（パブリッシュ／サブスクライブ）です。",
    "通知の一斉配信、イベントの複数箇所への連携。",
    "パブサブ通知。配る＝SNS。SQS（ためる）との対比が頻出。",
    ["SQS"]),
  T("t-directconnect", "AWS Direct Connect", "technology", 2,
    "オンプレとAWSを結ぶ専用線。",
    "インターネットを通さず、自社とAWSを専用の回線で直結します。安定して速く、大容量の通信ができます。",
    "安定・低遅延・大容量の接続が必要なハイブリッド構成。",
    "専用線接続。安定重視＝Direct Connect、手軽さ＝VPN。",
    ["VPC"]),
  // ---------------- security ----------------
  T("t-kms", "AWS KMS", "security", 2,
    "暗号鍵を一元管理するサービス。",
    "データを暗号化するための「鍵」を安全に作成・保管・管理できるサービスです。多くのサービスと連携します。",
    "S3やEBSなどのデータを暗号化したいとき。",
    "Key Management Service。暗号鍵の管理＝KMS。保存データ暗号化の中心。",
    ["S3", "EBS"]),
  T("t-cloudtrail", "AWS CloudTrail", "security", 2,
    "誰が何を操作したかを記録。",
    "「いつ・誰が・どの操作をしたか」を記録する、AWSの操作履歴（監査ログ）です。",
    "不正操作の調査、監査の証跡を残したいとき。",
    "操作の記録＝CloudTrail。監視のCloudWatchと混同注意。",
    ["Config", "CloudWatch"]),
  T("t-config", "AWS Config", "security", 2,
    "リソース設定の変更を追跡・評価。",
    "サーバーやストレージの設定が変わった履歴を記録し、決めたルールに違反していないかを継続的にチェックします。",
    "設定の正しさを保ちたい、コンプライアンスを維持したいとき。",
    "設定の監視＝Config。あるべき状態からのズレを検知。",
    ["CloudTrail"]),
  T("t-guardduty", "Amazon GuardDuty", "security", 2,
    "不審な挙動を自動検知する脅威検知。",
    "ログを自動で分析し、不正アクセスや異常な通信などの怪しい動きを見つけて知らせてくれる見張り役です。",
    "アカウントへの脅威を継続的に監視したいとき。",
    "脅威検知＝GuardDuty。Inspector（脆弱性診断）/Macie（機微データ）と区別。",
    ["Inspector", "Macie"]),
  T("t-cognito", "Amazon Cognito", "security", 2,
    "アプリのログイン機能を提供。",
    "自分のアプリに「会員登録」「ログイン」の仕組みを簡単に追加できるサービスです。利用者の認証を担います。",
    "モバイル/Webアプリの利用者向けサインアップ・ログイン。",
    "エンドユーザーの認証＝Cognito。社員向けはIAM Identity Center。",
    ["IAM"]),
  T("t-secretsmanager", "AWS Secrets Manager", "security", 2,
    "パスワード等の機密情報を安全に保管。",
    "データベースのパスワードやAPIキーなどの秘密情報を安全にしまい、自動で更新（ローテーション）もできます。",
    "アプリの認証情報をコードに直書きせず安全に管理したいとき。",
    "機密情報の保管＝Secrets Manager。自動ローテーション対応。",
    ["KMS"]),
  T("t-waf", "AWS WAF", "security", 2,
    "Webアプリを攻撃から守る盾。",
    "SQLインジェクションなど、Webサイトを狙う攻撃をルールで見分けて遮断するファイアウォールです。",
    "公開Webアプリを不正アクセスから守りたいとき。",
    "Web Application Firewall。CloudFront/ALBの前段。Shield（DDoS）と区別。",
    ["Shield", "CloudFront"]),
  // ---------------- billing ----------------
  T("t-costexplorer", "AWS Cost Explorer", "billing", 1,
    "コストをグラフで分析・可視化。",
    "これまでにかかった費用を、グラフや内訳で振り返って分析できるツールです。",
    "コストの傾向を把握し、無駄を見つけたいとき。",
    "振り返り＝Cost Explorer、先回りの管理＝Budgets。対で覚える。",
    ["Budgets"]),
  T("t-savingsplans", "AWS Savings Plans", "billing", 2,
    "一定利用のコミットで柔軟に割引。",
    "「毎時いくら使う」と決めて契約すると、対象の料金が安くなる仕組み。リザーブドより使い方の縛りがゆるいのが特長です。",
    "継続利用が見込めるコンピュート費用を安くしたいとき。",
    "コミットで割引。リザーブドより柔軟。コスト最適化の定番。",
    ["EC2"]),
  T("t-pricingcalculator", "AWS Pricing Calculator", "billing", 1,
    "使う前に料金を見積もるツール。",
    "これから作る構成を入力して、月額のおよその費用を事前に試算できるツールです。",
    "導入前に予算を組みたいとき。",
    "事前見積もり＝Pricing Calculator。導入前の試算に使う。",
    ["Budgets"]),
  T("t-support", "AWSサポートプラン", "billing", 1,
    "4段階のサポート提供レベル。",
    "困ったときの支援レベルを選ぶプラン。Basic（無料）/Developer/Business/Enterpriseの4段階です。",
    "運用体制に合わせてサポートの手厚さを選びたいとき。",
    "Basic/Developer/Business/Enterprise。24時間対応はBusiness以上、専任TAMはEnterprise。",
    ["Trusted Advisor"]),
  // ---------------- cloudConcepts ----------------
  T("t-region-az", "リージョンとアベイラビリティーゾーン", "cloudConcepts", 1,
    "AWSの世界的な拠点構造。",
    "リージョンは東京・大阪などの地域、その中に物理的に離れた複数のデータセンター群（AZ）があります。",
    "障害に強い構成（複数AZ配置）を理解するとき。",
    "リージョン＞AZ。複数AZ配置で高可用性。エッジロケーションはCDN用。",
    ["CloudFront"]),
  T("t-availability", "高可用性と弾力性", "cloudConcepts", 1,
    "止まらない・需要に合わせる設計思想。",
    "高可用性＝壊れても止まらないこと、弾力性＝必要に応じて自動で増減すること。クラウド設計の基本です。",
    "システムを安定運用しつつコストも抑えたいとき。",
    "単一障害点をなくす＝高可用性、自動増減＝弾力性。似た用語を区別。",
    ["Auto Scaling", "ELB"]),
  T("t-caf", "AWS CAF（クラウド導入フレームワーク）", "cloudConcepts", 2,
    "組織のクラウド移行を導く枠組み。",
    "会社全体でクラウドへ移るための道しるべ。技術だけでなく人や組織の準備も6つの視点で整理します。",
    "全社的なクラウド移行を計画するとき。",
    "6つの視点（ビジネス/人材/ガバナンス/プラットフォーム/セキュリティ/オペレーション）。人の再教育＝People。",
    ["Well-Architected フレームワーク"]),
];

// マージ（既存id優先）
const byId = new Map(existing.map((t) => [t.id, t]));
let addedCount = 0;
for (const t of added) {
  if (!byId.has(t.id)) { byId.set(t.id, t); addedCount++; }
}
const merged = Array.from(byId.values());
fs.writeFileSync(file, JSON.stringify(merged, null, 2) + "\n", "utf8");

console.log(`既存: ${existing.length} / 追加: ${addedCount} / 合計: ${merged.length}`);
const byDom = {};
merged.forEach((t) => (byDom[t.domain] = (byDom[t.domain] || 0) + 1));
console.log("分野別:", byDom);
